const actionTypes = Object.freeze({
    FETCH_ALL_ATTENDANCE_TODAY_SUCCED:'FETCH_ALL_ATTENDANCE_TODAY_SUCCED',
    FETCH_ALL_ATTENDANCE_TODAY_FAILED:'FETCH_ALL_ATTENDANCE_TODAY_FAILED'
})

export default actionTypes;